[define]
; define layers and their order
layers = #(#TEX_DIFFUSE, #TEX_STRUCTURE, #TEX_OVERLAY, #TEX_OVERLAY_CHANNEL, #TEX_ENVIRONMENT, #TEX_NMAP, #TEX_BUMP, #TEX_LM, #TEX_UNI, #DTA_WATER, #DTA_GLASS)

[TEX_DIFFUSE]
; define rollout label
label = Diffuse
; define texture ID
texID = 1
; define rollout items and their tab-stop order
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_STRUCTURE]
label = Structure
texID = 2
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_OVERLAY]
label = Overlay
texID = 3
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnOverlay, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_ENVIRONMENT]
label = Environment
texID = 4
items = #(#itgBitmap, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_NMAP]
label = Normal Map
texID = 5
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_BUMP]
label = Bump
texID = 6
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_LM]
label = Light Map
texID = 7
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnApplyLight, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_UNI]
label = Universal
texID = 8
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[TEX_OVERLAY_CHANNEL]
label = Overlay Channel
texID = 9
items = #(#itgBitmap, #btnMipmap, #btnTexMove, #btnTileU, #spnTilingU, #btnTileV, #spnTilingV, #spnChannel, #btnExtend, #btnFilename, #btnFindObject, #BtnUndefine, #btnReload, #btnShowBitmap, #btnShowAlpha, #btnShowTransp, #lbl2, #lblSize)

[DTA_WATER]
label = Water properties
texID = 10
items = #(#grp1, #spnShiftX, #spnShiftY, #spnShiftU, #spnShiftV, #grp2, #spnBlend, #grp3, #spnDiff1, #spnDiff2, #spnEnv, #grp4, #spnAngle)

[DTA_GLASS]
label = Glass properties
texID = 11
items = #(#grp2, #spnBlend, #grp3, #spnDiff1, #spnDiff2, #spnEnv, #grp4, #spnAngle)

[global]
TEX_STRUCTURERolledUp=true
TEX_OVERLAYRolledUp=true
TEX_OVERLAY_CHANNELRolledUp=true
TEX_ENVIRONMENTRolledUp=true
TEX_NMAPRolledUp=true
TEX_BUMPRolledUp=true
TEX_LMRolledUp=true
TEX_UNIRolledUp=true
MaxMatRolloutRolledUp=false
roSurfaceRolledUp=false
roLayersRolledUp=false
TEX_DIFFUSERolledUp=false
ShaderType=specular
SubShaderType=diffuse
